name: tests artifacts

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
        description: "release number"
      dry-run:
        required: true
        type: boolean
        description: "blank run means that the release will not be pushed"

jobs:
  test-sdist:
    name: test tarball archive of ${{ inputs.release-version }} ${{ inputs.dry-run && '(dry-run)' || '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v4
        with:
          pattern: pypi_files
          path: dist
          merge-multiple: true

      - name: "Install"
        run: |
          pip install dist/aioxmlrpc-*.whl --force-reinstall

      - name: "Test sdist"
        run: |
          python -c "from aioxmlrpc import __version__; print(__version__, end='')"
